

# This file was *autogenerated* from the file Testing3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4)########################################################################################################
#                                                                                                      #
#  Project:  Physics TFG                                                                               #
#  Author:   Sergio Casta√±eiras Morales                                                                #
#  Date:     06/02/2025                                                                                #
#  Purpose:  Testing                                                                                   #
#                                                                                                      #
########################################################################################################

i = _sage_const_4 
G = SymmetricGroup(i) 
print(f"Printing S{i}:")
show(G.cayley_table())

